services:
  core:
    build: backend
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    entrypoint: ["sh", "entrypoint.sh"]
    ports:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres_db
    environment:
      - POSTGRES_HOST=postgres_db

  frontend:
    build: connect-frontend
    volumes:
      - angular-build_volume:/app/dist
    command: npm run build --prod

  postgres_db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - angular-build_volume:/usr/share/nginx/html
    depends_on:
      core:
        condition: service_started
      frontend:
        condition: service_started

volumes:
  postgres_data:
  static_volume:
  media_volume:

  angular-build_volume:
