TEXT_BANNED = 'Вы забанены для заблокировки обратитесь к админу'
TEXT_PRODUCT_ORDER = 'Заказать товар'
TEXT_WHAT_IS_CONNECT = 'Что такое connect3?'
TEXT_REGISTER = 'Зарегистрироваться'
TEXT_MENU = 'Выбор меню'