# Generated by Django 5.0.6 on 2024-08-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=20, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='know_from',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Откуда узнал'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR-код пользователя'),
        ),
    ]
