# Generated by Django 5.0.6 on 2024-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userextended_about_me_userextended_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram Username'),
        ),
    ]
