# Generated by Django 5.0.6 on 2024-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userextended_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='phone_number',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Telegram Phone Number'),
            preserve_default=False,
        ),
    ]
