# Generated by Django 5.0.6 on 2024-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userextended_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('surname', models.CharField(max_length=124)),
                ('inspiration', models.CharField(max_length=124)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/', verbose_name='Фото спикера')),
            ],
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('surname', models.CharField(max_length=124)),
                ('inspiration', models.CharField(max_length=124)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teammate/', verbose_name='Фото команда')),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AddField(
            model_name='userextended',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photo/', verbose_name='Фото пользователя'),
        ),
    ]
