# Generated by Django 5.0.6 on 2024-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userextended_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
