# Generated by Django 5.0.6 on 2024-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userextended_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('surname', models.CharField(max_length=124)),
                ('inspiration', models.CharField(max_length=124)),
            ],
        ),
    ]
