# Generated by Django 5.0.6 on 2024-07-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siteconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('welcome_text', models.TextField(max_length=255, verbose_name='Приветственное письмо в тг боте')),
                ('what_is_connect', models.TextField(max_length=255, verbose_name='Что такое connect3?')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
