# Generated by Django 5.0.6 on 2024-07-01 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Siteconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField(max_length=255, verbose_name='Приветственное письмо в тг боте')),
                ('kitchen_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_admin_siteconfigs', to=settings.AUTH_USER_MODEL, verbose_name='Главный на кухне')),
                ('main_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_admin_siteconfigs', to=settings.AUTH_USER_MODEL, verbose_name='Главный админ')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
