# Generated by Django 5.0.6 on 2024-07-29 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='kitchen_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_admin_siteconfigs', to=settings.AUTH_USER_MODEL, verbose_name='Главный на кухне'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='main_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_admin_siteconfigs', to=settings.AUTH_USER_MODEL, verbose_name='Главный админ'),
        ),
    ]
