# Generated by Django 5.0.6 on 2024-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='what_is_connect',
            field=models.TextField(default=1, max_length=255, verbose_name='Что такое connect3?'),
            preserve_default=False,
        ),
    ]
