# Generated by Django 5.0.3 on 2024-05-07 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts",
            options={
                "ordering": ["-id"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
