# Generated by Django 5.0.6 on 2024-07-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Готово'),
        ),
    ]
